### ISSUE TITLE
Fail to read multi-image.ome.zarr when on local filesystem

### ISSUE THREAD

**Issue by jkh1** [ome/ome-ngff-prototypes#6]
Not sure if it's a problem with the Napari plugin used for reading or a problem with the downloaded file from https://oc.embl.de/index.php/s/0TPPw4CUt0G6nng.
See https://github.com/ome/napari-ome-zarr/issues/63

**Comment by constantinpape** [comment]
Hey @jkh1, it seems you were able to fix this with a napari upgrade in https://github.com/ome/napari-ome-zarr/issues/63.
So it looks like this is not an issue with the data. Can we close this one as well?

**Comment by jkh1** [comment]
Sure. Sorry I forgot to do it. Closing now.
